version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.77
#    depends_on:
#      - breedbase_db
    container_name: breedbase_web
    ports:
      - 8080:8080
      - 25:25
    volumes:
      - type: bind
        source: ${HOME}/hornwortbase/sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: /export/prod/public_hornwortbase/archive
        target: /home/production/archive
      - type: bind
        source: /export/prod/public_hornwortbase/tmp
        target: /home/production/tmp
      - type: bind
        source: /export/prod/public_hornwortbase/cache
        target: /home/production/cache
      - type: bind
        source: /export/prod/public_hornwortbase/cluster
        target: /home/production/cluster
      - type: bind
        source: /export/prod/public_hornwortbase/blast
        target: /home/production/blast
      - type: bind
        source: /export/prod/public_hornwortbase/images
        target: /home/production/images
      - type: bind
        source: ${HOME}/hornwortbase
        target: /home/production/cxgn/hornwortbase

#  breedbase_db:
#    image: breedbase/pg12:v0.5
#    container_name: breedbase_db
#    ports:
#      - 5431:5432
#    volumes:
#     - type: bind
#       source: /home/production/pgdata
#       target: /var/lib/postgresql/data
